### ISSUE TITLE
Such a great project

### ISSUE THREAD

**Issue by alexclaydon** [projectstorm/dynamouse#1]
Just to say that I found this project through HN, love it, and would absolutely pay for it if that was the direction you decided to take it! Thanks for your great work.

The first time I fired it up was one of those rare "Eureka!" moments.

**Comment by dylanvorster** [comment]
Thank you so much :D I was working in my music studio and was like "FINE I GUESS I'LL DO IT MYSELF >_>" Ive since found one or two small issues, and I'm going to try work on it this weekend. Thanks again for the kind words :)
